# Change these first
owner: ayrshare # Your GitHub organization or username, where this repository lives
repo: uptime-status # The name of this repository

sites:
  - name: Ayrshare App
    url: https://app.ayrshare.com
    icon: https://app.ayrshare.com/ayrshare-purple-icon.jpg
  - name: Ayrshare Website
    url: https://www.ayrshare.com
    icon: https://app.ayrshare.com/icon.png
  - name: /user API endpoint
    url: https://app.ayrshare.com/api/user
    icon: https://app.ayrshare.com/rest-api.png
    headers:
      - "Authorization: Bearer $API_KEY"
      - "Content-Type: application/json"
  - name: /post Twitter API Post
    url: https://app.ayrshare.com/api/post/random
    icon: https://app.ayrshare.com/rest-api.png
    method: POST
    headers:
      - "Authorization: Bearer $API_KEY"
      - "Content-Type: application/json"
    body: '{ "post": "Check on me.", "platforms": ["twitter"] }'
  - name: /post Facebook API Post
    url: https://app.ayrshare.com/api/post/random
    icon: https://app.ayrshare.com/rest-api.png
    method: POST
    headers:
      - "Authorization: Bearer $API_KEY"
      - "Content-Type: application/json"
    body: '{ "post": "Check on me.", "platforms": ["facebook"] }'
  - name: /post Instagram API Post
    url: https://app.ayrshare.com/api/post/random
    icon: https://app.ayrshare.com/rest-api.png
    method: POST
    headers:
      - "Authorization: Bearer $API_KEY"
      - "Content-Type: application/json"
    body: '{ "post": "Check on me.", "platforms": ["instagram"], "unsplash": { "type": "random", "size": "small", "options": { "orientation": "squarish" } } }'
  - name: /post LinkedIn API Post
    url: https://app.ayrshare.com/api/post/random
    icon: https://app.ayrshare.com/rest-api.png
    method: POST
    headers:
      - "Authorization: Bearer $API_KEY"
      - "Content-Type: application/json"
    body: '{ "post": "Check on me.", "platforms": ["linkedin"] }'
  - name: /post Telegram API Post
    url: https://app.ayrshare.com/api/post/random
    icon: https://app.ayrshare.com/rest-api.png
    method: POST
    headers:
      - "Authorization: Bearer $API_KEY"
      - "Content-Type: application/json"
    body: '{ "post": "Check on me.", "platforms": ["telegram"] }'

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # baseUrl: /uptime-status # where "repo" is your repository name
  name: Ayrshare Status
  logoUrl: https://app.ayrshare.com/ayrshare-purple-icon.jpg
  favicon: https://app.ayrshare.com/icon.png
  cname: status.ayrshare.com
  introTitle: "**Ayrshare** - an API for social posting and management."
  introMessage: The uptime status of [Ayrshare's](https://www.ayrshare.com) website, app. and APIs. Login to the [Ayrshare Dashboard](https://app.ayrshare.com).
  scripts:
    - src: https://plausible.io/js/plausible.js
      defer: true
      async: true
      data-domain: "ayrshare.com"
  navbar:
    - title: Ayrshare Home
      href: https://www.ayrshare.com
    - title: API Docs
      href: https://docs.ayrshare.com
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/30 * * * *"
